id: P404490DF
initial_creation_type: input
source_metadata:
  title: Magnetizing Series
  language: es
  description: 'Texts on the theme of magnetizing or bringing under one’s control
    (dbang du sdud pa):'
  volume:
    7a5058bcb91e4bb29d2a0c5f77fb9394:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    1dd63271c1c84fdb8bd0b06632fbadfa:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    fb0c9c96c036485bb2429a45c70307c1:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
created_at: '2022-03-01T04:30:45.115237'
last_modified_at: '2022-03-01T04:30:45.115239'
